//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionClient.TransactionCreditService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransactionCreditService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PerformCreditTransaction", ReplyAction="http://tempuri.org/IService1/PerformCreditTransactionResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Mandatory)]
        bool PerformCreditTransaction(string creditAccountID, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PerformCreditTransaction", ReplyAction="http://tempuri.org/IService1/PerformCreditTransactionResponse")]
        System.Threading.Tasks.Task<bool> PerformCreditTransactionAsync(string creditAccountID, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAccountDetails", ReplyAction="http://tempuri.org/IService1/GetAccountDetailsResponse")]
        decimal GetAccountDetails(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAccountDetails", ReplyAction="http://tempuri.org/IService1/GetAccountDetailsResponse")]
        System.Threading.Tasks.Task<decimal> GetAccountDetailsAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TransactionClient.TransactionCreditService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TransactionClient.TransactionCreditService.IService1>, TransactionClient.TransactionCreditService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool PerformCreditTransaction(string creditAccountID, double amount) {
            return base.Channel.PerformCreditTransaction(creditAccountID, amount);
        }
        
        public System.Threading.Tasks.Task<bool> PerformCreditTransactionAsync(string creditAccountID, double amount) {
            return base.Channel.PerformCreditTransactionAsync(creditAccountID, amount);
        }
        
        public decimal GetAccountDetails(int id) {
            return base.Channel.GetAccountDetails(id);
        }
        
        public System.Threading.Tasks.Task<decimal> GetAccountDetailsAsync(int id) {
            return base.Channel.GetAccountDetailsAsync(id);
        }
    }
}
